name: godot-haskell
synopsis: Haskell bindings for the Godot game engine API
description: This package contains Haskell bindings for GDNative and the Godot API. For details and examples, see README.md
version: '3.1.0.0'
category: Web
author: David Kraeutmann
maintainer: kane@kane.cx
copyright: 2018 David Kraeutmann
license: BSD3
github: KaneTW/godot-haskell
extra-source-files:
- README.md
- cbits/*

dependencies:
- base
- aeson
- bytestring
- template-haskell
- th-abstraction
- lens
- text
- casing
- vector
- containers
- unordered-containers
- mtl
- stm
- extra

pkg-config-dependencies:
- godot-headers

default-extensions:
- FlexibleContexts
- FlexibleInstances
- ScopedTypeVariables
- TypeApplications
- StandaloneDeriving
- DerivingStrategies
- DefaultSignatures
- MultiParamTypeClasses
- FunctionalDependencies
- TypeFamilies
- TemplateHaskell
- TypeOperators
- TypeInType
- QuasiQuotes
- OverloadedStrings
- PatternSynonyms
- GeneralizedNewtypeDeriving

executables:
  godot-haskell-project-generator:
    main: Main.hs
    source-dirs: project-generator
    pkg-config-dependencies:
    - godot-headers
    dependencies:
      - fsnotify
      - directory
      - filepath
      - interpolate
      - lens

library:
  source-dirs: src
  build-tools:
  - c2hs
  include-dirs:
  - cbits
  pkg-config-dependencies:
  - godot-headers
  dependencies:
  - split
  - generate
  - linear
  - colour

internal-libraries:
  generate:
    source-dirs: src-generate
    dependencies:
    - parsec
    - parsers
    - mtl
    - ansi-wl-pprint

ghc-options:
  - -O0
